name: 'slack-notify'
description: 'Send Slack notifications'
inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
    default: ''
  content:
    description: 'Content to be sent to the incoming webhook, in JSON format'
    required: true
    default: '{ text: "Content not set" }'
runs:
  using: 'node12'
  main: 'index.js'
